### PR TITLE
New command called 'operations'

### PR DESCRIPTION
**Pull request by ApplicationCoding**
It can be seen now when the command 'help' is typed and is now functioning as well.

### CODE REVIEW

**Comment by ApplicationCoding** [comment]
@YojanProductions , please review so that I can close this pull request. If you have any suggestions as well, please comment here or create a new issue.

**Comment by ApplicationCoding** [comment]
To check the feature, please download the latest version of Calculator: https://github.com/ApplicationCoding/calculator/releases/tag/v1.6.0

**Review by YojanProductions — APPROVED** [review]
dog

**Comment by ApplicationCoding** [comment]
LOL. Even at development, dog is stuck in your mind.

**Comment by ApplicationCoding** [comment]
But thanks.

**Pull request closed without merging**
